# Generated by Django 6.0.6 on 2026-06-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_data',
            field=models.FileField(blank=True, upload_to='musics/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='playlist',
            field=models.ManyToManyField(blank=True, to='music.playlist'),
        ),
    ]
